# Generated by Django 4.2.7 on 2026-05-06 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., My 3-Day Beach Adventure', max_length=200)),
                ('start_point', models.CharField(max_length=200)),
                ('end_point', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('stops', models.JSONField(default=list, help_text='List of stops with details')),
                ('notes', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='Share with other users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Itinerary',
                'verbose_name_plural': 'Itineraries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('beach', 'Beach'), ('water', 'Water Activity'), ('land', 'Land Activity'), ('hike', 'Hike'), ('food', 'Food Outlet'), ('site', 'Site to Visit')], max_length=20)),
                ('item_id', models.IntegerField(help_text='ID of the beach/activity/site')),
                ('item_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('duration_hours', models.FloatField(default=2.0, help_text='Estimated time to spend')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_stops', to='itinerary.itinerary')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
